# analytics/save_recommendation.py

def save_recommendation(
    cursor,
    user_product_id,
    current_price,
    recommended_price,
    demand_score,
    inventory_level,
    strategy,
    reason,
    avg_comp_price=None,
    min_comp_price=None,
    max_comp_price=None,
    parity_price_calc=None,
    inventory_price_calc=None,
    demand_price_calc=None
):

    cursor.execute("""
            INSERT INTO pricing_recommendations
            (
                user_product_id,
                current_price,
                average_competitor_price,
                lowest_competitor_price,
                highest_competitor_price,
                demand_score,
                inventory_level,
                recommended_price,
                pricing_strategy,
                recommendation_reason,
                generated_at,
                parity_price_calc,
                inventory_price_calc,
                demand_price_calc
            )
            VALUES
            (
                %s,
                %s,
                %s,
                %s,
                %s,
                %s,
                %s,
                %s,
                %s,
                %s,
                NOW(),
                %s,
                %s,
                %s
            )
        """,
        (
            user_product_id,
            current_price,
            avg_comp_price,
            min_comp_price,
            max_comp_price,
            demand_score,
            inventory_level,
            recommended_price,
            strategy,
            reason,
            parity_price_calc,
            inventory_price_calc,
            demand_price_calc
        ))